// components/landing/FeaturesSection.tsx
export default function FeaturesSection() {
  const features = [
    {
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-yellow-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      ),
      title: "Get Paid Instantly",
      description: "Solve issues and receive Bitcoin rewards immediately via Lightning Network. No waiting periods, no intermediaries.",
      points: [
        "Fast Bitcoin Lightning payments",
        "No minimum payout thresholds",
        "Earn in the hardest money available"
      ],
      bgColor: "bg-yellow-50"
    },
    {
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
        </svg>
      ),
      title: "Contribute Meaningfully",
      description: "Work on real issues in projects that align with your interests and values. Build your reputation in the open source community.",
      points: [
        "Focus on projects you believe in",
        "Build your open source portfolio",
        "Join a community of like-minded devs"
      ],
      bgColor: "bg-blue-50"
    },
    {
      icon: (
        <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-yellow-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
        </svg>
      ),
      title: "Project Management",
      description: "Project maintainers can incentivize contributions, attract quality developers, and manage bounties efficiently.",
      points: [
        "Attract top developer talent",
        "Set custom bounty amounts",
        "Track progress & manage contributions"
      ],
      bgColor: "bg-yellow-50"
    }
  ];

  return (
    <section id="features" className="py-16 md:py-24 bg-white">
      <div className="container mx-auto px-4 sm:px-6">
        <div className="text-center mb-12 md:mb-16">
          <div className="inline-block bg-yellow-100 text-yellow-800 px-3 py-1 rounded-full text-sm font-semibold mb-3">
            Platform Features
          </div>
          <h2 className="text-3xl md:text-4xl font-bold text-blue-900">Why Choose SatQuest?</h2>
          <p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">
            The open source contribution marketplace powered by Bitcoin Lightning Network
          </p>
        </div>
        
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-10">
          {features.map((feature, index) => (
            <div key={index} className="bg-white p-6 md:p-8 rounded-xl shadow-md border border-gray-100 hover:shadow-xl transition duration-300 transform hover:-translate-y-1">
              <div className={`w-14 h-14 ${feature.bgColor} rounded-lg flex items-center justify-center mb-6`}>
                {feature.icon}
              </div>
              <h3 className="text-xl font-bold text-blue-900 mb-3">{feature.title}</h3>
              <p className="text-gray-600">
                {feature.description}
              </p>
              <ul className="mt-4 space-y-2 text-sm text-gray-500">
                {feature.points.map((point, i) => (
                  <li key={i} className="flex items-center">
                    <svg className="w-4 h-4 mr-2 text-yellow-500" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path>
                    </svg>
                    {point}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// src/lib/components/landing/FeaturesSection.svelte
<section id="features" class="py-16 md:py-24 bg-white">
  <div class="container mx-auto px-4 sm:px-6">
    <div class="text-center mb-12 md:mb-16">
      <div class="inline-block bg-accent-100 text-accent-800 px-3 py-1 rounded-full text-sm font-semibold mb-3">
        Platform Features
      </div>
      <h2 class="text-3xl md:text-4xl font-bold text-primary-900">Why Choose SatQuest?</h2>
      <p class="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">
        The open source contribution marketplace powered by Bitcoin Lightning Network
      </p>
    </div>
    
    <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-10">
      <!-- Feature 1 -->
      <div class="bg-white p-6 md:p-8 rounded-xl shadow-soft border border-gray-100 hover:shadow-xl transition duration-300 transform hover:-translate-y-1">
        <div class="w-14 h-14 bg-accent-100 rounded-lg flex items-center justify-center mb-6">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-accent-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </div>
        <h3 class="text-xl font-bold text-primary-900 mb-3">Get Paid Instantly</h3>
        <p class="text-gray-600">
          Solve issues and receive Bitcoin rewards immediately via Lightning Network. No waiting periods, no intermediaries.
        </p>
        <ul class="mt-4 space-y-2 text-sm text-gray-500">
          <li class="flex items-center">
            <svg class="w-4 h-4 mr-2 text-accent-500" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
            </svg>
            Fast Bitcoin Lightning payments
          </li>
          <li class="flex items-center">
            <svg class="w-4 h-4 mr-2 text-accent-500" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
            </svg>
            No minimum payout thresholds
          </li>
          <li class="flex items-center">
            <svg class="w-4 h-4 mr-2 text-accent-500" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
            </svg>
            Earn in the hardest money available
          </li>
        </ul>
      </div>

      <!-- Feature 2 -->
      <div class="bg-white p-6 md:p-8 rounded-xl shadow-soft border border-gray-100 hover:shadow-xl transition duration-300 transform hover:-translate-y-1">
        <div class="w-14 h-14 bg-primary-100 rounded-lg flex items-center justify-center mb-6">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-primary-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
          </svg>
        </div>
        <h3 class="text-xl font-bold text-primary-900 mb-3">Contribute Meaningfully</h3>
        <p class="text-gray-600">
          Work on real issues in projects that align with your interests and values. Build your reputation in the open source community.
        </p>
        <ul class="mt-4 space-y-2 text-sm text-gray-500">
          <li class="flex items-center">
            <svg class="w-4 h-4 mr-2 text-accent-500" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
            </svg>
            Focus on projects you believe in
          </li>
          <li class="flex items-center">
            <svg class="w-4 h-4 mr-2 text-accent-500" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
            </svg>
            Build your open source portfolio
          </li>
          <li class="flex items-center">
            <svg class="w-4 h-4 mr-2 text-accent-500" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
            </svg>
            Join a community of like-minded devs
          </li>
        </ul>
      </div>

      <!-- Feature 3 -->
      <div class="bg-white p-6 md:p-8 rounded-xl shadow-soft border border-gray-100 hover:shadow-xl transition duration-300 transform hover:-translate-y-1">
        <div class="w-14 h-14 bg-accent-100 rounded-lg flex items-center justify-center mb-6">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 text-accent-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
          </svg>
        </div>
        <h3 class="text-xl font-bold text-primary-900 mb-3">Project Management</h3>
        <p class="text-gray-600">
          Project maintainers can incentivize contributions, attract quality developers, and manage bounties efficiently.
        </p>
        <ul class="mt-4 space-y-2 text-sm text-gray-500">
          <li class="flex items-center">
            <svg class="w-4 h-4 mr-2 text-accent-500" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
            </svg>
            Attract top developer talent
          </li>
          <li class="flex items-center">
            <svg class="w-4 h-4 mr-2 text-accent-500" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
            </svg>
            Set custom bounty amounts
          </li>
          <li class="flex items-center">
            <svg class="w-4 h-4 mr-2 text-accent-500" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
            </svg>
            Track progress & manage contributions
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
