// src/lib/components/landing/HeroSection.svelte
<section class="bg-blue-900 text-white py-16 md:py-24">
  <div class="container mx-auto px-4 sm:px-6">
    <div class="max-w-4xl mx-auto text-center">
      <h1 class="text-4xl md:text-5xl lg:text-6xl font-bold mb-4 leading-tight">
        Earn Bitcoin for Open Source Contributions
      </h1>
      <p class="text-lg md:text-xl mb-8 text-blue-100 max-w-3xl mx-auto">
        SatQuest connects developers with Bitcoin-incentivized GitHub issues. Solve problems, get paid instantly via Lightning Network.
      </p>
      
      <!-- CTAs -->
      <div class="flex flex-col sm:flex-row gap-4 justify-center">
        <a href="/explore" class="px-6 py-3 bg-yellow-400 text-blue-900 rounded-lg font-medium hover:bg-yellow-300 transition duration-300 inline-flex items-center justify-center shadow-lg hover:shadow-xl transform hover:-translate-y-1">
          <span>Browse Issues</span>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 ml-2" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L12.586 11H5a1 1 0 110-2h7.586l-2.293-2.293a1 1 0 010-1.414z" clip-rule="evenodd" />
          </svg>
        </a>
        <a href="/learn-more" class="px-6 py-3 border-2 border-blue-400 text-white rounded-lg font-medium hover:bg-blue-800 transition duration-300 inline-flex items-center justify-center">
          Learn How It Works
        </a>
      </div>
      
      <!-- Stats Cards -->
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mt-12">
        <div class="bg-blue-800 rounded-lg p-4 shadow-lg">
          <div class="text-2xl md:text-3xl font-bold text-yellow-400">250+</div>
          <div class="text-sm text-blue-200">Active Issues</div>
        </div>
        <div class="bg-blue-800 rounded-lg p-4 shadow-lg">
          <div class="text-2xl md:text-3xl font-bold text-yellow-400">120+</div>
          <div class="text-sm text-blue-200">Open Source Projects</div>
        </div>
        <div class="bg-blue-800 rounded-lg p-4 shadow-lg">
          <div class="text-2xl md:text-3xl font-bold text-yellow-400">₿12.5</div>
          <div class="text-sm text-blue-200">Total Bounties</div>
        </div>
        <div class="bg-blue-800 rounded-lg p-4 shadow-lg">
          <div class="text-2xl md:text-3xl font-bold text-yellow-400">950+</div>
          <div class="text-sm text-blue-200">Developers</div>
        </div>
      </div>
    </div>
  </div>
</section>

// components/landing/HeroSection.tsx
import Link from 'next/link';

export default function HeroSection() {
  return (
    <section className="bg-blue-900 text-white py-20">
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-5xl md:text-6xl font-bold mb-6">
            Earn Bitcoin for Open Source Contributions
          </h1>
          <p className="text-xl mb-10">
            Connect with Bitcoin-incentivized GitHub issues and get rewarded for your valuable contributions to open source projects.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
            <Link 
              href="/dashboard" 
              className="bg-yellow-400 hover:bg-yellow-500 text-blue-900 font-bold py-3 px-8 rounded-lg transition-colors"
            >
              Browse Issues
            </Link>
            <Link 
              href="#how-it-works" 
              className="bg-transparent hover:bg-white/10 border-2 border-white py-3 px-8 rounded-lg transition-colors"
            >
              Learn How It Works
            </Link>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mt-12">
            {[
              { label: 'Active Issues', value: '250+' },
              { label: 'Open Source Projects', value: '120+' },
              { label: 'Total Bounties', value: '₿ 5.8' },
              { label: 'Developers', value: '1,500+' }
            ].map((stat, index) => (
              <div key={index} className="bg-blue-800/50 rounded-lg p-6 backdrop-blur-sm">
                <p className="text-4xl font-bold text-yellow-400">{stat.value}</p>
                <p className="text-lg">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
